jumpserver-master/jlog/urls.py
# coding:utf-8
from django.conf.urls import patterns, include, url
from jlog.views import *

urlpatterns = patterns('',
                       url(r'^list/(\w+)/$', log_list, name='log_list'),
                       url(r'^detail/(\w+)/$', log_detail, name='log_detail'),
                       url(r'^history/$', log_history, name='log_history'),
                       url(r'^log_kill/', log_kill, name='log_kill'),
                       url(r'^record/$', log_record, name='log_record'),
                      )

jumpserver-master/jumpserver/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('jumpserver.views',
    # Examples:
    url(r'^$', 'index', name='index'),
    # url(r'^api/user/$', 'api_user'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^skin_config/$', 'skin_config', name='skin_config'),
    url(r'^login/$', 'Login', name='login'),
    url(r'^logout/$', 'Logout', name='logout'),
    url(r'^exec_cmd/$', 'exec_cmd', name='exec_cmd'),
    url(r'^file/upload/$', 'upload', name='file_upload'),
    url(r'^file/download/$', 'download', name='file_download'),
    url(r'^setting', 'setting', name='setting'),
    url(r'^terminal/$', 'web_terminal', name='terminal'),
    url(r'^juser/', include('juser.urls')),
    url(r'^jasset/', include('jasset.urls')),
    url(r'^jlog/', include('jlog.urls')),
    url(r'^jperm/', include('jperm.urls')),
    # url(r'^gateone/',include('webssh.urls')),
    url(r'docker/',include('docker_manage.urls')),
    url(r'docker_cluster/',include('docker_cluster.urls')),


)

jumpserver-master/jasset/models.py
# coding: utf-8

import datetime
from django.db import models
from juser.models import User, UserGroup

ASSET_ENV = (
    (1, U'生产环境'),
    (2, U'STAG环境'),
    (3, u"总部Ceph"),
    (4, u"Virtual"),
    )

ASSET_STATUS = (
    (1, u"已使用"),
    (2, u"未使用"),
    (3, u"报废")
    )

ASSET_TYPE = (
    (1, u"物理机"),
    (2, u"虚拟机"),
    (3, u"交换机"),
    (4, u"路由器"),
    (5, u"防火墙"),
    (6, u"Docker"),
    (7, u"其他")
    )


class AssetGroup(models.Model):
    GROUP_TYPE = (
        ('P', 'PRIVATE'),
        ('A', 'ASSET'),
    )
    name = models.CharField(max_length=80, unique=True)
    comment = models.CharField(max_length=160, blank=True, null=True)

    def __unicode__(self):
        return self.name


class IDC(models.Model):
    name = models.CharField(max_length=32, verbose_name=u'机房名称')
    bandwidth = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'机房带宽')
    linkman = models.CharField(max_length=16, blank=True, null=True, default='', verbose_name=u'联系人')
    phone = models.CharField(max_length=32, blank=True, null=True, default='', verbose_name=u'联系电话')
    address = models.CharField(max_length=128, blank=True, null=True, default='', verbose_name=u"机房地址")
    network = models.TextField(blank=True, null=True, default='', verbose_name=u"IP地址段")
    date_added = models.DateField(auto_now=True, null=True)
    operator = models.CharField(max_length=32, blank=True, default='', null=True, verbose_name=u"运营商")
    comment = models.CharField(max_length=128, blank=True, default='', null=True, verbose_name=u"备注")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u"IDC机房"
        verbose_name_plural = verbose_name


class Asset(models.Model):
    """
    asset modle
    """
    ip = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"主机IP")
    other_ip = models.CharField(max_length=255, blank=True, null=True, verbose_name=u"其他IP")
    hostname = models.CharField(unique=True, max_length=128, verbose_name=u"主机名")
    port = models.IntegerField(blank=True, null=True, verbose_name=u"端口号")
    group = models.ManyToManyField(AssetGroup, blank=True, verbose_name=u"所属主机组")
    username = models.CharField(max_length=16, blank=True, null=True, verbose_name=u"管理用户名")
    password = models.CharField(max_length=256, blank=True, null=True, verbose_name=u"密码")
    use_default_auth = models.BooleanField(default=True, verbose_name=u"使用默认管理账号")
    idc = models.ForeignKey(IDC, blank=True, null=True,  on_delete=models.SET_NULL, verbose_name=u'机房')
    mac = models.CharField(max_length=20, blank=True, null=True, verbose_name=u"MAC地址")
    # remote_ip = models.CharField(max_length=16, blank=True, null=True, verbose_name=u'远控卡IP')
    remote_ip = models.OneToOneField('Idrac',blank=True, null=True, verbose_name=u'远控卡IP')
    brand = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'硬件厂商型号')
    cpu = models.CharField(max_length=64, blank=True, null=True, verbose_name=u'CPU')
    memory = models.CharField(max_length=128, blank=True, null=True, verbose_name=u'内存')
    disk = models.CharField(max_length=1024, blank=True, null=True, verbose_name=u'硬盘')
    system_type = models.CharField(max_length=32, blank=True, null=True, verbose_name=u"系统类型")
    system_version = models.CharField(max_length=8, blank=True, null=True, verbose_name=u"系统版本号")
    system_arch = models.CharField(max_length=16, blank=True, null=True, verbose_name=u"系统平台")
    cabinet = models.CharField(max_length=32, blank=True, null=True, verbose_name=u'机柜号')
    position = models.IntegerField(blank=True, null=True, verbose_name=u'机器位置')
    number = models.CharField(max_length=32, blank=True, null=True, verbose_name=u'资产编号')
    status = models.IntegerField(choices=ASSET_STATUS, blank=True, null=True, default=1, verbose_name=u"机器状态")
    asset_type = models.IntegerField(choices=ASSET_TYPE, blank=True, null=True, verbose_name=u"主机类型")
    env = models.IntegerField(choices=ASSET_ENV, blank=True, null=True, verbose_name=u"运行环境")
    sn = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"SN编号")
    date_added = models.DateTimeField(auto_now=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name=u"是否激活")
    comment = models.CharField(max_length=128, blank=True, null=True, verbose_name=u"备注")

    def __unicode__(self):
        return self.hostname


class AssetRecord(models.Model):
    asset = models.ForeignKey(Asset)
    username = models.CharField(max_length=30, null=True)
    alert_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)


class AssetAlias(models.Model):
    user = models.ForeignKey(User)
    asset = models.ForeignKey(Asset)
    alias = models.CharField(max_length=100, blank=True, null=True)

    def __unicode__(self):
        return self.alias


# 租户信息 add by Rain
class Tenant_info(models.Model):
    env_type_value = (
        ("stag", u"staging环境"),
        ("prod", u"生产环境"),
    )
    env_type = models.CharField(u"环境类型", choices=env_type_value, max_length=32, default="stag")
    tenant_name = models.CharField(max_length=48,verbose_name=u'租户名称')
    user_name = models.CharField(max_length=48,verbose_name=u'用户名')
    user_passwd = models.CharField(max_length=48,verbose_name=u'密码')
    admin_host = models.CharField(max_length=1024,verbose_name=u'管理主机',null=True,blank=True)
    net_work = models.CharField(max_length=1024,verbose_name=u'管理网络',null=True,blank=True)
    comments = models.TextField(max_length=1024,verbose_name=u'备注信息',null=True,blank=True)

    class Meta:
        verbose_name = "租户信息"
        verbose_name_plural = "租户信息"

    def __unicode__(self):
        return self.tenant_name

# Idrac 信息
class Idrac(models.Model):
    Idrac_ip = models.GenericIPAddressField(verbose_name=u"IDRAC管理地址")
    Idrac_user = models.CharField(max_length=48, verbose_name=u"Idrac管理用户", null=True, blank=True)
    Idrac_passwd = models.CharField(max_length=48, verbose_name=u'IDrac管理密码', null=True, blank=True)

    class Meta:
        verbose_name = "Idrac"

    def __unicode__(self):
        return self.Idrac_ip

# 主机信息 add by Rain
# class Host_info(models.Model):
#     env_type_value = (
#         ("stag", u"staging环境"),
#         ("prod", u"生产环境"),
#         ("zongbu", u"总部Ceph"),
#         ("virtual", u"Virtual"),
#     )
#     env_type = models.CharField(u"环境类型", choices=env_type_value, max_length=32, default="stag",null=True,blank=True)
#     host_name = models.CharField(verbose_name=u"服务器名称", max_length=48)
#     SN = models.CharField(verbose_name=u"服务器SN号", max_length=126,null=True,blank=True)
#     host_ip = models.GenericIPAddressField(verbose_name=u"服务器IP地址")
#     host_models = models.CharField(max_length=48, verbose_name=u"服务器型号",null=True,blank=True)
#     host_port = models.CharField(max_length=48,verbose_name=u'SSH port',null=True,blank=True,default=22)
#     host_user = models.CharField(max_length=48,verbose_name=u"主机用户",null=True,blank=True)
#     host_passwd = models.CharField(max_length=48,verbose_name=u"主机密码",null=True,blank=True)
#     Idrac = models.OneToOneField(Idrac,null=True,blank=True)
#     comments = models.TextField(verbose_name=u"备注",null=True,blank=True)
#
#     class Meta:
#         verbose_name = "主机信息"
#         verbose_name_plural = "主机信息"
#
#     def __unicode__(self):
#         return self.host_name


# 管理地址
class Url_info(models.Model):
    url = models.URLField()
    env_type_value = (
        ("stag", u"staging环境"),
        ("prod", u"生产环境"),
        ("shijiazhuang", u"石家庄环境"),
        ("office", u"生产环境"),
    )
    env_type = models.CharField(u"环境类型", choices=env_type_value, max_length=32, default="staging")
    server_name = models.CharField(verbose_name=u"服务名称",max_length=48,null=True,blank=True)
    user_name = models.CharField(max_length=48,verbose_name=u"登录名",null=True,blank=True)
    user_passwd = models.CharField(max_length=48,verbose_name=u"密码",null=True,blank=True)
    host_type = models.CharField(max_length=48,verbose_name=u"主机类型",null=True,blank=True)
    comments = models.TextField(verbose_name=u"备注",null=True,blank=True)

    class Meta:
        verbose_name = "管理地址"
        verbose_name_plural = "管理地址"

    def __unicode__(self):
        return self.url



# 虚拟化平台
class Virtual_platform(models.Model):
    virtual_type_value = (
        ("Xenserver", "Xenserver"),
        ("Vmware", "Vmware"),
    )
    platform_name = models.CharField(u'平台名称', max_length=48)
    virtual_type = models.CharField(u"虚拟化类型", choices=virtual_type_value, max_length=48,null=True,blank=True)
    zone = models.CharField(verbose_name=u"区域", max_length=48,null=True,blank=True)
    # host_info = models.OneToOneField(Host_info,verbose_name=u'主机信息',null=True,blank=True)
    host_info = models.OneToOneField(Asset, verbose_name=u'主机信息', null=True, blank=True)
    class Meta:
        verbose_name = "虚拟主机平台"
        verbose_name_plural = "虚拟主机平台"

    def __unicode__(self):
        return self.platform_name


# 虚拟化主机
class Virtual_host(models.Model):
    host_ip = models.GenericIPAddressField(verbose_name=u"虚拟主机IP")
    host_name = models.CharField(max_length=48, verbose_name=u"虚拟主机名称")
    # host_user = models.CharField(max_length=48,verbose_name=u'用户名',null=True,blank=True)
    # host_passwd = models.CharField(max_length=48, verbose_name=u'密码',null=True,blank=True)
    host_comments = models.CharField(max_length=128,verbose_name=u"备注",blank=True,null=True)
    server = models.ForeignKey("Virtual_platform")

    class Meta:
        verbose_name = "虚拟主机"
        verbose_name_plural = "虚拟主机"

    def __unicode__(self):
        return self.host_ip

jumpserver-master/docker_manage/forms.py
# coding:utf-8
from django import forms
from  api import  *
from models import  docker_conf
def get_choice():
    host_choice = ()
    mydocker = Docker_manage()
    for host in mydocker.all_docker_images.keys():
        temp_choice = (host, host)
        host_choice += (temp_choice,)
    images_choice = ()
    try:
        host, image_list = mydocker.all_docker_images.items()[0]
        for image in image_list:
            temp_choice = (image["RepoTags"][0], image["RepoTags"][0])
            images_choice += (temp_choice,)
    except Exception as e:
        print e
        host_choice = ""
        images_choice = ""
    # print images_choice
    return  host_choice,images_choice

def get_volume(docker_host):
    mydocker = Docker_manage()
    volume_choice = ()
    all_volumes = mydocker.volume_list(docker_host)
    for host,volumes  in all_volumes.items():
        print host,volumes
        for volume in volumes["Volumes"]:
            temp_choice  = ("%s_%s"%(host,volume["Mountpoint"]),volume["Name"])
            volume_choice +=(temp_choice,)
    return volume_choice


# mount type
def get_mount_type():
    mount_type_choice = (
        ('auto',u'自动创建数据卷'),
        ('nomount',u'不挂载数据卷'),
        ('input',u'手动指定'),
    )
    return  mount_type_choice

def get_port():
    port_choice = (
        ("default",u'默认'),
        ("port",u"端口"),
        # ("portrange",u"端口范围"),
    )
    return port_choice


class create_container(forms.Form):
    def __init__(self, *args, **kwargs):
        # dynamic loading ....
        super(create_container, self).__init__(*args, **kwargs)
        self.fields["docker_host"].choices = get_choice()[0]
        self.fields["container_images"].choices = get_choice()[1]
        # self.fields["volume_name"].choices = get_volume("all")
        self.fields["mount_type"].choices = get_mount_type()
        self.fields["port_type"].choices = get_port()

    container_name = forms.CharField(label=u'容器名称',max_length=48)
    host_name = forms.CharField(label=u'主机名称',max_length=48)
    docker_host = forms.ChoiceField(label=u'容器主机',widget=forms.widgets.Select(choices=(),attrs={
        'class':"form-control",
        "onchange":"change_host(this)",
    }))
    container_images = forms.ChoiceField(label=u'容器镜像',widget=forms.widgets.Select(choices=(),attrs={
        'class':"form-control",
    }))

    port_type  = forms.ChoiceField(label=u'容器端口',widget=forms.widgets.Select(
        attrs={
            'class': "form-control",
            "onclick": "change_port_type(this)",
        }
    ))
    port = forms.CharField(label=u"端口",widget=forms.widgets.Input(
        attrs={
            'placeholder': "8000:8080;7096:8096  请按照此格式添加 容器端口:宿主机端口;容器端口:宿主机端口",
        }

    ))
    mount_type = forms.ChoiceField(label=u'数据卷挂载',widget=forms.widgets.Select(
        attrs={
            'class': "form-control",
            "onclick": "change_mount_type(this)",
        }
    ))

    volume_name  = forms.ChoiceField(label=u'数据卷',widget=forms.widgets.Select(
        attrs={
            'class': "form-control",
        }
    ))
    docker_mount = forms.CharField(max_length=128,label=u'数据卷挂载位置')

    command = forms.CharField(label=u'命令',max_length=128)

    # host_choice, images_choice = get_choice()



class pull_image_form(forms.Form):
    host_choice, images_choice = get_choice()
    registry = forms.CharField(label=u'registry',max_length=128,widget=forms.widgets.Input(attrs={
        'placeholder':"docker.io",
        'value':"docker.io",
        }))
    search_name = forms.CharField(label=u'search',max_length=128)
    docker_host = forms.CharField(label=u'容器主机',max_length=48,widget=forms.widgets.Select(choices=host_choice,attrs={
        'class':"form-control",
    }))




class create_volume(forms.Form):
    def __init__(self, *args, **kwargs):
        # dynamic loading ....
        super(create_volume, self).__init__(*args, **kwargs)
        self.fields["docker_host"].choices = get_choice()[0]
    docker_host = forms.ChoiceField(label=u'容器主机',widget=forms.widgets.Select(choices=(),attrs={
        'class':"form-control",
    }))
    volume_name = forms.CharField(label=u'Volume name',max_length=48)


class docker_edit_form(forms.Form):
    docker_name = forms.CharField(label=u'容器新名称',max_length=128)


class docker_conf_form(forms.ModelForm):
    class Meta:
        model = docker_conf
        fields = "__all__"

jumpserver-master/templates/docker/docker_create.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap %}
{% include 'nav_cat_bar.html' %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5> 填写Docker信息 </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    {% if emg %}
                        <div class="alert alert-warning text-center">{{ emg }}</div>
                    {% endif %}
                    {% if smg %}
                        <div class="alert alert-success text-center">{{ smg }}</div>
                    {% endif %}
                    <form id="URLForm" method="post" class="form-horizontal">


                         {% for item in docker_form %}
                                 <div class="col-sm-9">
                                     {{ item|bootstrap_horizontal }}
                                 </div>
{#                             <div class="hr-line-dashed"></div>#}
                         {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-5">
                                <button class="btn btn-white" type="submit"> 重置 </button>
                                <button class="btn btn-primary" type="sumbit"> 提交 </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
            var volume_obj = $("#id_volume_name");
            var option_html = "<option vlaue='Auto'>自动创建</option>";
            volume_obj.empty();
            volume_obj.append(option_html);
            $("#id_port").closest(".col-sm-9").hide();
    });
    function change_port_type(ths) {
        if($(ths).val()=="default"){
            $("#id_port").closest(".col-sm-9").hide();
        }else{
            $("#id_port").closest(".col-sm-9").show();

        }
    }
    function change_mount_type(ths) {
        if($(ths).val()=="auto"){
            $("#id_volume_name").closest('.col-sm-9').show();
            $("#id_docker_mount").closest('.col-sm-9').show();
            var volume_obj = $("#id_volume_name");
            var option_html = "<option vlaue='Auto'>自动创建</option>";
            volume_obj.empty();
            volume_obj.append(option_html);
        }else if($(ths).val()=="nomount"){
            $("#id_volume_name").closest('.col-sm-9').hide();
            $("#id_docker_mount").closest('.col-sm-9').hide();
        }else if($(ths).val()=="input"){
            $("#id_volume_name").closest('.col-sm-9').show();
            $("#id_docker_mount").closest('.col-sm-9').show();
            change_host($("#id_docker_host"));
        }


    }


    function change_host(ths){
        var option_html = "";
        var volume_obj = $("#id_volume_name");
{#        console.log($("#id_auto_volume")[0].checked);#}

        $.get("{% url 'docker_image_list' %}",{"docker_host":$(ths).val(),"query":"true"},function(data){
{#            console.log(data);#}
            var images  = $.parseJSON(data);
            var container_image = $("#id_container_images");
            container_image.empty();
            $.each(images,function () {
{#               console.log($(this));#}
                var new_item = $(this)[0].RepoTags[0];
                var item_html = "<option value="+new_item+">"+new_item+"</option>";
                container_image.append(item_html);


            });

        });
{#        volume #}
        if($("#id_mount_type").val()=="auto"){
            option_html = "<option vlaue='Auto'>自动创建</option>";
                volume_obj.empty();
                volume_obj.append(option_html);
        }else{
                $.get("{% url 'docker_volume_list' %}",{"docker_host":$(ths).val(),"query":"true"},function(data){
                    if(data!="null"){
                        volume_obj.removeAttr('disabled');
                        var a = $.parseJSON(data);
                        $.each(a,function () {
                            console.log($(this));
                            var name = $(this)[0].Name;
                            var value = $(this)[0].Mountpoint;
                            option_html += "<option value="+value+" >"+name+"</option>";
                        });
                        option_html += "<option vlaue=None>不挂载数据卷</option>";
                        volume_obj.empty();
                        volume_obj.append(option_html);
                    }else{
                        option_html += "<option vlaue=None >无可用数据卷</option>";
                        volume_obj.attr('disabled','disabled');
                        volume_obj.empty();
                        volume_obj.append(option_html);
                    }

                });
            }

    };
    var required_fields = ["id_url","id_server_name"];
    required_fields.forEach(function(field) {
        $('label[for="' + field + '"]').parent().addClass("required");
    });

    $('#URLForm').validator({
        timely: 2,
        theme: "yellow_right_effect",
        fields: {
            "#id_url": {
                rule: "required",
                tip: "输入URL",
                ok: "",
                msg: {required: "URL必须填写!"},
                data: {'data-ok':"URL可以使用", 'data-msg-required': 'URL已正确'}
            },
            "#id_server_name": {
                rule: "required",
                tip: "输入服务名称",
                ok: "",
                msg: {required: "服务名称必须填写!"},
                data: {'data-ok':"服务名称可以使用", 'data-msg-required': '服务名称已正确'}
            },

        },
        valid: function(form) {
            form.submit();
        }
    });
</script>

{% endblock %}

jumpserver-master/templates/docker/docker_image_pull.html
{% extends 'base.html' %}
{% block content %}
{% load bootstrap %}
{% include 'nav_cat_bar.html' %}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-10">
            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5> Search image </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">
                    {% if emg %}
                        <div class="alert alert-warning text-center">{{ emg }}</div>
                    {% endif %}
                    {% if smg %}
                        <div class="alert alert-success text-center">{{ smg }}</div>
                    {% endif %}
                    <div id="pull_image_form" class="form-horizontal">


                         {% for item in images_form %}
                             <div class="form-group">
                                 <div class="col-sm-9">
                                     {{ item|bootstrap_horizontal }}
                                 </div>
                             </div>
                             <div class="hr-line-dashed"></div>
                         {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-5">
                                <button class="btn btn-primary" onclick="search_image()"> Search </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="search_ret col-sm-8">
            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5> Search result </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content">

                </div>
            </div>
        </div>

        <div class="pull_progress col-sm-4">
            <div class="ibox float-e-margins">
                <div id="ibox-content" class="ibox-title">
                    <h5>Pull  progress </h5>
                    <div class="ibox-tools ">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>

                <div class="ibox-content pull_image_progress ">
                    <div class="hawkularqe/manageiq-test"></div>


                </div>
            </div>
        </div>
    </div>

</div>

<script>
$(document).ready(function(){
    $.get(
            '{% url "image_history" %}',
            {},
            function(data){
                $(".pull_image_progress").append(data);
{#                if(data=="true"){#}
{#                    bootbox.alert("remove ok..",reload_page);#}
{#                }#}
            }
    );
})
</script>

<script>
    function getRandomString(len) {
        len = len || 32;
        var $chars = 'ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678';
        var maxPos = $chars.length;
        var pwd = '';
        for (i = 0; i < len; i++) {
            pwd += $chars.charAt(Math.floor(Math.random() * maxPos));
        }
        return pwd;
    }


    function pull_image(ths) {
{#        console.log($(ths).html());#}
{#        console.log($(ths).closest("tr").html());#}
        var image_name = $(ths).closest("tr").find(".name").html();
        var registry = $("#id_registry").val();
        var docker_host = $("#id_docker_host").val();
        bootbox.alert("Start download.....");
        $.get("{% url 'pull_image' %}",{"image_name":image_name,"registry":registry,"docker_host":docker_host});
        var pull_div = $(".pull_image_progress");
        var image_random_id = getRandomString();
        pull_div.append("<div class="+image_random_id+">"+"<h5>"+image_name+"</h5>"+"</div>");

        var wsServer = 'ws://172.16.13.80:8088/docker/pull_image_progress'; //服务器地址
            var websocket = new WebSocket(wsServer); //创建WebSocket对象
            websocket.onopen = function (evt) {
                //已经建立连接
                console.log(websocket.readyState);
                websocket.send(image_name+"|"+docker_host);//向服务器发送消息
                //查看websocket当前状态
            };
            websocket.onclose = function (evt) {
                console.log("closed !!!!!!!!");
                //已经关闭连接
            };
            websocket.onmessage = function (evt) {
                console.log(evt.data);
                var progress = $.parseJSON(evt.data);
                if(progress.id){

                    var id = progress.id;
                    var ret  = JSON.stringify(progress.progress);
                    var status = progress.status;
                    if(status=="Already exists"){
                        ret = "Already exists";
                    }
                    var id_len = pull_div.find("."+id).length;

                    if(!ret){
                        ret="";
                    }

                    if(id_len!=0){
                        pull_div.find("."+id).text(id+":"+status+":"+ret);

                    }else{
                        var ret_html = "<div class="+id+">"+id+":"+ret+"</div>";

                        pull_div.find("."+image_random_id).append(ret_html);
                    }

                }
            };
    }

    function search_image(){
        var all_item = $("#pull_image_form").find("input[id^='id_'],select");
        console.log(all_item);
        var get_data= {};
        all_item.each(function () {
            get_data[$(this).attr("name")] = $(this).val()
        });
{#        console.log(get_data);#}
        $.get("{% url 'image_search' %}",get_data,function(data){

                $(".search_ret").find(".ibox-content").html(data);
        });

    }

    var required_fields = ["id_url","id_server_name"];
    required_fields.forEach(function(field) {
        $('label[for="' + field + '"]').parent().addClass("required");
    });

    $('#URLForm').validator({
        timely: 2,
        theme: "yellow_right_effect",
        fields: {
            "#id_url": {
                rule: "required",
                tip: "输入URL",
                ok: "",
                msg: {required: "URL必须填写!"},
                data: {'data-ok':"URL可以使用", 'data-msg-required': 'URL已正确'}
            },
            "#id_server_name": {
                rule: "required",
                tip: "输入服务名称",
                ok: "",
                msg: {required: "服务名称必须填写!"},
                data: {'data-ok':"服务名称可以使用", 'data-msg-required': '服务名称已正确'}
            },

        },
        valid: function(form) {
            form.submit();
        }
    });
</script>

{% endblock %}